### ISSUE TITLE
Add a .travis.yml file for CI and publishing to gh-pages

### ISSUE THREAD

**Issue by jyasskin** [privacycg/template#1]
https://github.com/w3cping/privacy-threat-model/blob/main/.travis.yml has something you can start with. The `before_deploy` gunk comes from https://docs.travis-ci.com/user/deployment-v2/providers/pages/#securing-secrets.

**Comment by hober** [comment]
This sounds like a great idea that I don't understand in the slightest. Hopefully we can get someone to set this up for us.

**Comment by jyasskin** [comment]
This was fixed by fbfe890f007b16ff949c044c5a19366d52aa6396.
