### ISSUE TITLE
Should the README include a reference to the Code of Conduct?

### ISSUE THREAD

**Issue by annevk** [privacycg/template#3]
We do this in the WHATWG and it seems somewhat helpful as otherwise you kinda have to know where to look. We could also do the CODE_OF_CONDUCT.md file I suppose with a pointer if that's still a thing.

**Comment by hober** [comment]
> We do this in the WHATWG and it seems somewhat helpful as otherwise you kinda have to know where to look.

Yeah, that's a good idea. We do this in other repos, IIRC. I'll try to do this today.

> We could also do the CODE_OF_CONDUCT.md file I suppose with a pointer if that's still a thing.

I think this is unnecessary clutter, since we have a [.github repo](https://github.com/privacycg/.github).

**Comment by annevk** [comment]
Given the .github repo and how that seems to work I'm no longer convinced that what I said is needed. That seems to work rather well.

**Comment by hober** [comment]
Okay. Closing!
